### ISSUE TITLE
Infer golangci-lint version from go.mod

### ISSUE THREAD

**Issue by lukasmalkmus** [golangci/golangci-lint-action#106]
For Go projects, I use `tools.go` to specify the tools the project depends on and pin the version in the `go.mod` file. This is pretty convenient. It would be awesome to have the action infer the version from the `go.mod` file. When upgrading, this makes it one file less to update the `golangci-lint` version.

With some guidance, I can probably tackle this. I'm just completely new to GitHub Actions.

**Comment by sayboras** [comment]
While `tools.go` is convenient to pin version of dependencies, it might dilute go.mod (or go.sum). I personally used both approach and recently moved away from tools.go. Version pinning is done in Makefile.

Anyway, I have very limited idea how widely tools.go is used. In general, I find it's great idea to derive version from go.mod. This might be done only after https://github.com/golangci/golangci-lint-action/issues/98, which supports patch version.

**Comment by sayboras** [comment]
@lukasmalkmus just curious if you are planning to work on this.

**Comment by lukasmalkmus** [comment]
Yes, sounds great. Wil. try to tackle it next weekend 👍

**Comment by sayboras** [comment]
@lukasmalkmus the related PR got merged, feel free to shout out if you have any question/concern.

**Comment by lukasmalkmus** [comment]
Sorry, I haven't really gotten into it, yet. I made a very simple implementation: #118. It tries to get the version from `go.mod` if nothing is specified in the action yaml. `npm run local` runs just fine but I would appreciate some guidance regarding testing.
