### ISSUE TITLE
Action is causing deprecation warnings

### ISSUE THREAD

**Issue by jannfis** [golangci/golangci-lint-action#111]
Recently, GitHub has deprecated the `set-env` and `add-path` commands that can be printed to stdout by an action, refer to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`golangci-lint-action` is making use of these in a couple of places, thus causing deprecation warnings in the action's annotations (and probably will stop working some day).

The deprecated commands should be replaced by using newly introduced [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)

**Comment by sayboras** [comment]
I think it's used internally in one of dependency (e.g. actions/*), currently latest version is used based on my understanding.

A quick `grep` for both set-env and add-path didn't help much, do you have do any specific place ?

**Comment by jannfis** [comment]
After a little more research, the issue seems to stem from something in the cache (in the `prepare-environment` step of the `golangci-lint-action`):

```
  Finding needed golangci-lint version...
  Setup go stable version spec 1
  Found in cache @ /opt/hostedtoolcache/go/1.15.2/x64
  Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  Added go to the path
  Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  Successfully setup go version 1
  go version go1.15.2 linux/amd64
```
So, maybe bumping up a cache version somewhere to invalidate old stuff might be the correct fix.

**Comment by sayboras** [comment]
Please upgrade to the latest version v2.2.1, sample run is available here https://github.com/golangci/golangci-lint/runs/1261488064

```
> prepare environment
  Finding needed golangci-lint version...
  Setup go stable version spec 1
  Found in cache @ /opt/hostedtoolcache/go/1.15.2/x64
  Added go to the path
  Successfully setup go version 1
  go version go1.15.2 linux/amd64
```

**Comment by jannfis** [comment]
Ah, I was under the impression that the `@v2` specified as the action's version would always use the latest version from the 2.x branch. 

So if I understood your pointer correctly, we shall replace `uses: golangci/golangci-lint-action@v2` with `uses: golangci/golangci-lint-action@v2.2.1`?

**Comment by sayboras** [comment]
currently, v2 is pointing to v2.0 or v2.1 only I think. I think github action convention to to tag only major version, which I don't prefer personally :).

Let me point v2 to v2.2.1 shortly, it was pending action in my note while released v2.2.1 recently. Thanks for reminder :100:

**Comment by sayboras** [comment]
Done, now v2 points to latest release v2.2.1.

**Comment by jannfis** [comment]
:tada: Now it doesn't generate the deprecation notices anymore! Thank you for the quick support :+1:
