### ISSUE TITLE
`--release-notes` + process substitution fails => unknown shorthand flag

### ISSUE THREAD

**Issue by lukasmalkmus** [golangci/golangci-lint-action#112]
I'll manage my changelog by hand and wrote a custom tool for my project to extract the appropriate section from the changelog and add that as release notes. But the solution proposed in the documentation doesn't work with the action. It works locally, so I guess the issue is related to the action.

This is the workflow step:

```yaml
- name: Release
  uses: goreleaser/goreleaser-action@v2
  with:
    args: release --rm-dist --release-notes <(./bin/changelog-extractor -f=CHANGELOG.md -t=${{ steps.tagName.outputs.tag }})
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This results in the following output:

```shell
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.145.0/x64/goreleaser release --rm-dist --release-notes <(./bin/changelog-extractor -f=CHANGELOG.md -t=v0.1.0)

   ⨯ command failed            error=unknown shorthand flag: 't' in -t=v0.1.0)
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.145.0/x64/goreleaser' failed with exit code 1
```

**Comment by bombsimon** [comment]
Did you mean to open this issue in the [goreleaser-action](https://github.com/goreleaser/goreleaser-action) repository? It doesn’t seem related to `golangci-lint`?

**Comment by lukasmalkmus** [comment]
Oh my god, my bad 😞 

Looks like I struggled with my browser tabs 😅 Well, I guess there's a first time for everything.
