### ISSUE TITLE
Error: options working-directory and only-new-issues aren't compatible

### ISSUE THREAD

**Issue by bojan-embroker** [golangci/golangci-lint-action#150]
Hi,

I tried setting both `working-directory` and `only-new-issues` but got: `Error: options working-directory and only-new-issues aren't compatible`

I am working on a monorepo and would like to be able to get only new issues from the linter. How hard would be to allow it?

**Comment by thebeline** [comment]
I am not familiar with the workings of a "monorepo" (I am new to `golang`), but as I understand it:

`golangci-lint` will (should?) only report issues in the changes included in the reference `patch`, which should only be changes actively made.  This also impacts how it makes it's annotations internally.

If you want to exclude changes that may be in other directories, please have a look at the `golangci-lint` [Configuration Options](https://golangci-lint.run/usage/configuration/).

**Comment by warber** [comment]
Hi, I am also using this action in the context of a mono repo. I've created one job for each project and set the `working-directory` field accordingly:

```
name: golangci-lint
on: [pull_request]
jobs:
  golangci-first-project:
    name: lint/first-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: first-project
  golangci-second-project:
    name: lint/second-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: second-project

The PullRequest contains only changed files of `first-project` but the linter is also checking and reporting findings in `second-project`
Do I need to configure the action differently?

**Comment by HarryMichal** [comment]
Hi! Our [project](https://github.com/containers/toolbox) has its source code in a subdirectory. Thus we need to set the `working-directory` option which leads to this error.
