### ISSUE TITLE
Allow disabeling go mod cache

### ISSUE THREAD

**Issue by smyrman** [golangci/golangci-lint-action#153]
There may be good reason for not letting this task restore, cache or download modules. E.g. in our case, we have _private_ dependencies that require setting the `GOPRIVATE` environment variable in order to resolve all dependencies. Besides, as we already save and restore the module cache for tests, why not reuse it for lint.

Therefore, having a way to _turn off_ module cache, in the same way you can configure to not install go, would be very handy.

**Comment by Jimeux** [comment]
I think this could also be a way of resolving https://github.com/golangci/golangci-lint-action/issues/135. People who generate their own cache could just disable the cache inside the action.

**Comment by smyrman** [comment]
If solving this, probably makes sense to allow disabling _build cache_ as well.
