### ISSUE TITLE
Create an issue when an update is available.

### ISSUE THREAD

**Issue by hsblhsn** [golangci/golangci-lint-action#157]
I'm always frustrated when a new update of golangci-lint is available, I need to find it out by myself.

I want the GitHub action to create an issue or PR when an update is available. A issue is enough to let me know that there's an update of `golangci-lint` is available. A PR would be great though.

I didn't consider a solution by myself yet.But I have subscribed to release notification on GitHub. But I almost always forget which of the repositories I have updated or not.

Thank you!

**Comment by SVilgelm** [comment]
The action supports using the latest golagci-lint, just use `latest` or remove the version of golangci-lint

**Comment by bombsimon** [comment]
It's also possible to get an automatic PR when a new version of an action you're using is released, see [dependabot](https://github.com/dependabot) (this just happened in the [`golangci-lint` repo this morning](https://github.com/golangci/golangci-lint/pull/1735)).
