### ISSUE TITLE
How to specify to only lint on new changes?

### ISSUE THREAD

**Issue by kortschak** [golangci/golangci-lint-action#16]
This used to exist in the golangci.com default configuration, but it's entirely unclear how to achieve this with the GitHub action. I've tried using the .golangci.yml configuration adapted from the YAML [here](https://golangci-lint.run/usage/configuration/), to no avail; I'd like to just leave it as default except for this.

```{yaml}
issues:
  new: true
```

**Comment by jirfag** [comment]
Hi,
I'm not sure should it be enabled by default or not. It's planned.

**Comment by kortschak** [comment]
Until then, is there a way to achieve the outcome via configuration?

**Comment by jirfag** [comment]
I guess something like this:
```yaml
args: --new-from-rev origin/master
```

**Comment by kortschak** [comment]
That doesn't seem to work https://github.com/gonum/gonum/pull/1328/checks?check_run_id=696172335

**Comment by jirfag** [comment]
we've supported `only-new-issues`
