### ISSUE TITLE
v2 tag wasn't updated

### ISSUE THREAD

**Issue by AlekSi** [golangci/golangci-lint-action#166]
Tag `v2` wasn't updated after `v2.4.0` was tagged. It should be moved for `golangci/golangci-lint-action@v2` to use 2.4.0.

**Comment by ernado** [comment]
Should we remove `v2` completely?

**Comment by AlekSi** [comment]
GitHub recommends re-tagging the latest release with `vMAJOR` tag. Alternatively, you may use `vMAJOR` branch for releases, and merge into that branch when you do a release. More here: https://docs.github.com/en/actions/creating-actions/about-actions#using-release-management-for-actions

**Comment by SVilgelm** [comment]
let me re-tag it

**Comment by SVilgelm** [comment]
I deleted the v2 tag in origin and created v2 tag for same commit
