### ISSUE TITLE
Go 1.16 issue

### ISSUE THREAD

**Issue by fabriciojs** [golangci/golangci-lint-action#183]
Hello! I have updated my project code to Go 1.16, including the methods moving away from `ioutil` to `os`/`io` packages.

And now our Github Action is failing with what makes me believe is a mismatch in Go versions.

Locally I am able to successfully execute with `docker run ... golangci/golangci-lint:v1.38.0 golangci-lint run -v` - 1.38 works on my Go 1.16 updated code.

Now under CI using this action I am getting: https://github.com/kool-dev/kool/pull/288/checks?check_run_id=2088452091

![image](https://user-images.githubusercontent.com/1116377/110833463-38c5af80-827b-11eb-9055-6fcc45b5998a.png)

I am leaned to think it can be some issue due to caching...

I am gonna continue my own investigation trying to fix it, but since didn't find a report here on the matter decided to open the ticket already in case someone can help or be helped afterward.

**Comment by SVilgelm** [comment]
Try to install go v1.16 and use `skip-go-installation: true`

**Comment by fabriciojs** [comment]
@SVilgelm thanks it worked - my change: https://github.com/kool-dev/kool/pull/288/commits/f068b004416bfa8493a628e543061326d40c3856
