### ISSUE TITLE
args: --disable-all || --disable smth not working

### ISSUE THREAD

**Issue by reggieoswald-ads** [golangci/golangci-lint-action#206]
<img width="402" alt="Screenshot 2021-04-05 at 15 45 30" src="https://user-images.githubusercontent.com/76565028/113575182-2ba3a280-9626-11eb-852f-f8bcdcdf42a9.png">
<img width="1322" alt="Screenshot 2021-04-05 at 15 45 02" src="https://user-images.githubusercontent.com/76565028/113575184-2cd4cf80-9626-11eb-82c2-fda6e583a9f7.png">

**Comment by thebeline** [comment]
I believe this is an issue with `golangci-lint`, as it seems the command line arguments are applied before the `.golangci.yml` options.  I ran in to this the other day when trying to only enable a select number of linters.  The `--disable-all` flag gets applied (or `--disable`), and then it applies any and all `enable` options in the `yml`.

The Action IS passing this argument to `golanci-lint`, it is just in how `golangci-lint` handles it.

If you want nothing to fail, I would suggest setting `--issues-exit-code 0`.  It will still run the full set of linters, it just will not fail.

If you want only certain linters to fail, and others to not, I have a PR inbound...

**Comment by ldez** [comment]
Typecheck is not real linter it's a way to handle errors, it cannot be disabled.

**Comment by thebeline** [comment]
Ah, right.
