### ISSUE TITLE
Can this run on macos-latest VM?

### ISSUE THREAD

**Issue by hu13** [golangci/golangci-lint-action#24]
I tried it out, but the action downloaded the wrong binary.

<img width="1286" alt="Screen Shot 2020-05-30 at 1 31 02 PM" src="https://user-images.githubusercontent.com/13399936/83335316-eed68480-a279-11ea-90a1-ed94eb13c252.png">

The reason why I opt to use macos-latest vm instead is that I can't get the ubuntu-latest to run and keep getting: `could not import C (cgo preprocessing failed)))))]"`.

**Comment by jirfag** [comment]
Hi,
currently, it runs only on linux.

I think we need also to research how it works with cgo and and add a test case for that.

**Comment by SVilgelm** [comment]
@hu13 Could you please test the #65 if it possible? I added the support of running the action on different platforms

**Comment by hu13** [comment]
@SVilgelm , confirmed it is working at `golangci/golangci-lint-action@platforms`
