### ISSUE TITLE
GitHub Annotations suppresses normal output

### ISSUE THREAD

**Issue by directionless** [golangci/golangci-lint-action#362]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I really love that the github action supports annotations. _But_ when using it, there is minimal other output. Specifically, while the message is printed, it lacks the file/line number. (And at least sometimes, Github itself doesn't display anything at all)

Everything _is_ in the annotations, but those don't display properly in a couple of cases:
1. Newly added linters may find things outside the PR. Those annotations are not displayed anywhere. (There's a note that they happened, but no link to a file and line number
2. If there are a _lot_ of failures, having a clear list would be helpful

I'm not sure if this is a bug or a feature request...

I'd suggest either a normal print along side the github actions print, or allowing multiple out-formats to be specified. 

### Version of golangci-lint

<details>
github actions

```console
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
```

</details>

### Configuration file

N/A

### Go environment

<details>

GitHub Actions

</details>

### Verbose output of running

No Output: <details>
<img width="486" alt="No Output" src="https://user-images.githubusercontent.com/179542/139349230-641619e7-feb0-410b-ac72-ee41b6f4068b.png">

</details>

Minimal Output: <details>
<img width="573" alt="Minimal Output" src="https://user-images.githubusercontent.com/179542/139349260-3642771b-f314-473a-bd8c-36b49ca1e429.png">
</details>

None of those include file/line number

### Code example or link to a public repository

https://github.com/kolide/launcher/runs/4039960409?check_suite_focus=true

**Comment by directionless** [comment]
My first thought had been multiple output formats, but on some reflection, just including the file/line number in the annotation maybe cleaner. Or both. I'm happy to try to put up a PR, though I don't know which of the 3 approaches is likely to be accepted.

**Comment by Emyrk** [comment]
I would really like the file + line number context in both areas as well.

**Comment by ldez** [comment]
In golangci-lint it's now possible to have multiple output formats.
Maybe it requires some changes inside the GitHub Action.

**Comment by zfy0701** [comment]
the problem of running lint twice makes the github page show error twice as well, e.g.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1646270/183885989-50aa7424-f640-4696-9eff-b65a7d262512.png">

but it still much better than no output. in some cases, not just line number but the detail error message will be eaten
