### ISSUE TITLE
[Question] Does golangci-lint-action support minor patches?

### ISSUE THREAD

**Issue by denis-tingajkin** [golangci/golangci-lint-action#38]
Look's like with golangci-lint-action I can't use golangci-lint with minor patches, for example, version: `v1.28.3` is not working. Is this behavior expected?

**Comment by SVilgelm** [comment]
What is wrong with `v1.28.3`?

But looks like this is the expected behavior:
```js
  if (parsedRequestedLintVersion.patch !== null) {
    throw new Error(
      `requested golangci-lint version '${requestedLintVersion}' was specified with the patch version, need specify only minor version`
    )
  }
```
https://github.com/golangci/golangci-lint-action/blob/master/src/version.ts#L53

**Comment by denis-tingajkin** [comment]
> What is wrong with v1.28.3?

There only one problem - I can not use it with golangci-lint-action :) 

Do we need to allow to use of minor patches?

**Comment by SVilgelm** [comment]
Could you provide more details? We tested it yesterday and it worked.
We had an issue with it, but it was resolved after we updated the assets.
Could you run one more time please, maybe it works now?
