### ISSUE TITLE
v1.2.2 was broke if using working-directory

### ISSUE THREAD

**Issue by cc4i** [golangci/golangci-lint-action#39]
For example: 
lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint for dice
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: ./dice
          args: --timeout 5m

Output err:
  Running [/home/runner/golangci-lint-1.26.0-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=./dice --timeout 5m] in [/home/runner/work/aws-solutions-assembler/aws-solutions-assembler/dice] ...
  level=error msg="Can't get config for command line: can't parse args: unknown flag: --path-prefix"

**Comment by sayboras** [comment]
@cc4i thanks for reporting this issue. 

Do you mind testing again with v1.28 ? Seems like v1.2.2 supports 1.28+ only, versioning strategy might need to be revised.

**Comment by SVilgelm** [comment]
Yeah, I think we need to change the minimum version and create one more release (1.2.3)

**Comment by SVilgelm** [comment]
We forgot to change the minimum version of golangci-lint that can be used, I prepared a patch with these changes and updated the README.md

**Comment by SVilgelm** [comment]
Here is the plans to fix it:
* merging #40 
* releasing `v1.2.3`
* deprecating `v1.2.2`
