### ISSUE TITLE
feature request: specify commit hash as golangci-lint version

### ISSUE THREAD

**Issue by ansiwen** [golangci/golangci-lint-action#525]
Would be great if it would be possible to use pre-release versions of `golangci-lint` by specifying a commit hash instead of a version string (as you can do with `go install).

**Comment by bewuethr** [comment]
Isn't that always possible, as long as you have a commit hash?

```yaml
uses: golangci/golangci-lint-action@05a61b80ab9743dd4e7ddafc2728db7db095fce3
```

**Comment by ansiwen** [comment]
That's for the version of the `golangci-lint-action`, not for actual `golangci-lint` tool.

**Comment by bewuethr** [comment]
Right! Duh :confused:

**Comment by ldez** [comment]
Close in favor of #540
