### ISSUE TITLE
multiple projects in a monorepo, annotations fail to be displayed

### ISSUE THREAD

**Issue by intUnderflow** [golangci/golangci-lint-action#529]
Hi folks,

I'm using golangci as a GitHub Action matrix to scan multiple projects in a monorepo, one issue I've struggled with though is that when this is done annotations fail to display on the pull requests? Is there a known issue and is there any workaround?

Thanks & super appreciate the help :)

**Comment by ldez** [comment]
The annotations have limitations: https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md#limitations
