### ISSUE TITLE
Allow building golangci-lint from source

### ISSUE THREAD

**Issue by SuperSandro2000** [golangci/golangci-lint-action#530]
To solve issues like https://github.com/golangci/golangci-lint-action/issues/442#issuecomment-1203786890 it would be cool if instead of downloading the precompiled binary you could either set a flag that golangci-lint is build from source or the user needs to download and install it in a previous step and the action just expects it to be in ``$PATH``.

**Comment by shahzadlone** [comment]
Sounds like a good idea! I found this is what was causing our builds to fail as we are on 1.18 and the precompiled 1.48 golangci-lint would keep using 1.19 golang rules, when the one built from source was working fine.

**Comment by ldez** [comment]
Close in favor of #540
