### ISSUE TITLE
Complaining about imports on unchanged files and linking to comments

### ISSUE THREAD

**Issue by noahdietz** [golangci/golangci-lint-action#534]
On a recent PR, golangci-lint started complaining about files that we not part of the PR, that didn't actually need a goimports run (we ran it on the entire repo with no delta), and it emitted the findings on comments in the file rather than the imports section.

Here is the offending [run](https://github.com/googleapis/api-linter/runs/7694258955).

Any idea what it could be?

**Comment by shwoodard** [comment]
Here's some photo evidence and a [link](https://github.com/googleapis/api-linter/pull/995/commits/82c3995487d759145c3d1fe4b400913d1f27af32) to support:

![image](https://user-images.githubusercontent.com/34149/183112466-fbd7f843-caa4-44ce-b107-4d551d1855ad.png)

Of note, it is finding issues in a directory that was not touched, and, as Noah said, it's linting a comment.

**Comment by L0ntra** [comment]
I'm having the same problem with issues being found in comments.
Running goimports on the "offending" files does nothing and running golangci-lint locally does not detect any issues.

**Comment by maratori** [comment]
Seems like relates to #535

**Comment by noahdietz** [comment]
> Seems like relates to #535

Indeed it does. I will let the maintainers decide which to de-dupe.

**Comment by SaxyPandaBear** [comment]
In order to fix this in my GitHub CI, I had to download Go 1.19 and run `go1.19 fmt ./...` on my repo, which performed the necessary formatting on the comment that it cared about. My project is pinned to go1.18 so 🤷
