### ISSUE TITLE
Improve dependabot PR/process

### ISSUE THREAD

**Issue by sayboras** [golangci/golangci-lint-action#55]
yeah, we need to investigate how to automate this as well. The main entry point is coming from this line https://github.com/golangci/golangci-lint-action/blob/master/action.yml#L27

_Originally posted by @sayboras in https://github.com/golangci/golangci-lint-action/pull/54#issuecomment-658457208_

**Comment by SVilgelm** [comment]
we can do for any push to master branch run npm run all and if the files in dist folder were changed, then just make a direct commit to the master branch using. But we need a GitHub token with admin permissions for this repo

or just block from merging, so someone need to do it manually and update a PR

the dependabot creates the local branches, so anyone from the team can checkout those branches, change it and push the changes back
