### ISSUE TITLE
failed to load packages: timed out to load packages: context deadline exceeded

### ISSUE THREAD

**Issue by irl-segfault** [golangci/golangci-lint-action#560]
Hey there,

Added a new workflow definition to our repo as defined in the README, verbatim.  Tried pushing up a PR and got the following.

```Run golangci/golangci-lint-action@v3
  with:
    version: v1.46
    github-token: ***
    only-new-issues: false
    skip-cache: false
    skip-pkg-cache: false
    skip-build-cache: false
prepare environment
  Finding needed golangci-lint version...
  Requested golangci-lint 'v1.46', using 'v1.46.2', calculation took 63ms
  Installing golangci-lint v1.46.2...
  Downloading https://github.com/golangci/golangci-lint/releases/download/v1.46.2/golangci-lint-1.46.2-linux-amd64.tar.gz ...
...
  Running [/home/runner/golangci-lint-1.46.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
  
  Error: golangci-lint exit with code 4
```

Any ideas here? What would cause a vanilla Go repo to not work with the default config?

**Comment by ldez** [comment]
Hello,
I think your repo is large or with a lot of dependencies, you have to increase the timeout as suggested in the logs.

**Comment by maxforasteiro** [comment]
hey @ldez, it seems that the timeout flag is not available as for now on the action (according to the docs) do you know if it's too much work to add it?

**Comment by maxforasteiro** [comment]
nvm, I can do something like https://github.dev/golangci/golangci-lint-action/blob/5acb063f68ce921cd1e8380310270f54ccbca0e4/.github/workflows/test.yml#L83 I already answered my own question hahaha
