### ISSUE TITLE
Verify golangci organization and get the verified badge on Github Marketplace

### ISSUE THREAD

**Issue by vaihtovirta** [golangci/golangci-lint-action#579]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

We'd like to use `golangci-lint-action` in our pipeline, but by our company's policy, it's only allowed to use verified GitHub actions.
So it'd be great to verify [golangci](https://github.com/golangci) organization, so the other users with similar policies could use it in their projects.

### Describe the solution you'd like.

Apply for publisher verification, as described here: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization
The process seems to be pretty straightforward

### Describe alternatives you've considered.

We could fork the GitHub action into our organization so it's compliant with the policy.

### Additional context.

The same request was posted here: https://github.com/golangci/golangci-lint-action/issues/87#issuecomment-790672163

**Comment by huornlmj** [comment]
+1

**Comment by ldez** [comment]
🎉 It was not an easy journey, but now the organization is a verified publisher.

**Comment by ldez** [comment]
Sad news, the verified publisher process is not related to the "Verified Creator" badge for an action...

https://github.com/orgs/community/discussions/25265#discussioncomment-3247173

It seems that [GitHub’s Partner program](https://partner.github.com/) is the only way to actually obtain verification.

**Comment by ldez** [comment]
I asked the question to GitHub support, we will wait for an official and clear answer.

**Comment by ldez** [comment]
The official answer from GitHub support:

> Hi Ludovic,
> 
> Thanks for reaching out. Please note that the publisher verification process is currently applicable only to Apps and not Actions.
> 
> Only GitHub partner organizations can receive a Verified Creator badge for Actions. Currently, there is no way to request verification. Creators are verified because they have an existing relationship with GitHub, and GitHub has worked closely with the creator to create their actions. We are continuing to evaluate this process, and we may open it up more broadly in the future.
> 
> I hope this clarifies things and if we can be of further assistance, please let us know.
> 
> Best,
> Jack

So I will close this issue because it's impossible for an organization like golangci to get the verified badge on GitHub Marketplace for the action.
