### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by KasonBraley** [golangci/golangci-lint-action#708]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

golangci-lint action is failing in multiple repositories with the following error.
 
```
Error: Failed to run: Error: failed to get action config: certificate has expired, Error: failed to get action config: certificate has expired
    at /home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:68139:15
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:68044:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: failed to get action config: certificate has expired
Received 112481080 of 112481080 (100.0%), 131.5 MBs/sec
Cache Size: ~107 MB (112481080 B)
```

### Version of golangci-lint

latest

### Version of the GitHub Action

v3

### Workflow file

<details>

```
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -E goimports --timeout=5m --out-${NO_FUTURE}format colored-line-number
```

</details>

### Go version

1.20

### Code example or link to a public repository

See above

**Comment by andrejpetras** [comment]
I have the same problem

**Comment by crazy-max** [comment]
Looks related to https://www.githubstatus.com/incidents/x7njwb481j9b

**Comment by KasonBraley** [comment]
> Looks related to https://www.githubstatus.com/incidents/x7njwb481j9b

Thank you, nice find. I can confirm that running the workflows again worked.
