### ISSUE TITLE
GitHub token isn't exposed on forked pull requests

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint-action#9]
See golangci/golangci-lint#1072.

The issue is that [secrets are not passed to workflows that are triggered by a pull request from a fork](https://help.github.com/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

Currently this action uses github token to find the latest patch version of specified minor release.

My idea is to generate `version-maps.json` in `golangci-lint` repository and download it for detecting a last patch version. Using GitHub API without tokens can fail because of 60 req/hour rate limit.

**Comment by ernado** [comment]
Can we use standard `GITHUB_TOKEN`  https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow ?

**Comment by jirfag** [comment]
looks like it works, thank you @ernado !

**Comment by jirfag** [comment]
and we can get rid of it as a simplifying feature in #11
