### ISSUE TITLE
Can the release of version `node20` be considered?

### ISSUE THREAD

**Issue by 178inaba** [golangci/golangci-lint-action#953]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

I have received the following warning.

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: golangci/golangci-lint-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### Describe the solution you'd like.

I would like a version released using node20 to address the warning.

### Describe alternatives you've considered.

None.

### Additional context.

v3.7.0 (latest version): node16
https://github.com/golangci/golangci-lint-action/blob/3a919529898de77ec3da873e3063ca4b10e7f5cc/action.yml#L45

master: node20
https://github.com/golangci/golangci-lint-action/blob/e38f9440960e1e2614c17215b6ec8ce95f0c0719/action.yml#L45

**Comment by azisaka** [comment]
while we don't get a new version you can replace `uses: golangci/golangci-lint-action@v3` by `uses: golangci/golangci-lint-action@master`

**Comment by 178inaba** [comment]
@azisaka 
Thank you for the reply! I also considered that approach, but it seems that specifying branches is not recommended in the Actions documentation.

> Using the default branch of an action may be convenient, but if someone releases a new major version with a breaking change, your workflow could break.
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

> Under this release management approach, users should not be referencing an action's default branch, as it's likely to contain the latest code and consequently might be unstable. Instead, you can recommend that your users specify a major version when using your action, and only direct them to a more specific version if they encounter issues.
> https://docs.github.com/en/actions/creating-actions/about-custom-actions#good-practices-for-release-management

**Comment by rhussmann** [comment]
@178inaba one more workaround that doesn't depend on a moving ref

```
uses: golangci/golangci-lint-action@c67416616c29c3c48d26b59c45cadb56966d80aa
```

where `c67416616c29c3c48d26b59c45cadb56966d80aa` is the full commit SHA where `action.yml` was updated to point to `node20`.

Still looking forward to seeing a persistent tag published with this support as I'd prefer not to have to rely on a specific commit.

**Comment by ldez** [comment]
Done https://github.com/golangci/golangci-lint-action/tags
v3 updated and v3.7.1 created.

**Comment by 178inaba** [comment]
@ldez Thanks!

**Comment by lukestoward** [comment]
@ldez ideally this change should have been a new major version as the other standard actions managed the upgrade. See [actions/cache](https://github.com/actions/cache/releases/tag/v4.0.0), [actions/setup-go](https://github.com/actions/setup-go/releases/tag/v5.0.0) etc.

This has broken our pipeline as a result. Easily fixed, but we will have to pin the version to `v3.7.0` now instead of using `@3`.

**Comment by ldez** [comment]
Sorry, I will create a v4 and try to restore previous v3.

**Comment by ldez** [comment]
I moved the tag v3 to v3.7.0 and created v4 and v4.0.0

I'll keep v3.7.1 to avoid being too breaking.

**Comment by lukestoward** [comment]
Great, thanks for the quick resolution!
