### ISSUE TITLE
Add release notes for v4.0.0

### ISSUE THREAD

**Issue by rootulp** [golangci/golangci-lint-action#974]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

I got a dependabot PR to bump to golangci-lint-action v4.0.0. I went to the release notes: https://github.com/golangci/golangci-lint-action/releases/tag/v4.0.0 and don't see any breaking changes. I don't know if it's safe to bump to this release. I don't know what motivated the major version bump.

### Describe the solution you'd like.

Please update the release notes in https://github.com/golangci/golangci-lint-action/releases/tag/v4.0.0 with the breaking changes that motivated the major version bump. Ideally the release notes describe what functionality has changed or requires manual intervention from users who use this action.

### Describe alternatives you've considered.

N/A

### Additional context.

N/A

**Comment by ldez** [comment]
Done
