### ISSUE TITLE
bump action runtime to `node20`

### ISSUE THREAD

**Issue by tamirkiviti13** [golangci/golangci-lint-action#975]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Your feature request related to a problem? Please describe.

GitHub now deprecated the `node16` runtime for actions and requested to change the actions to use `node20`. Using this action causes a warning in the job - https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Describe the solution you'd like.

Bumping the action version to `node20` runtime

### Describe alternatives you've considered.

Bumping the action version to `node20` runtime

**Comment by bombsimon** [comment]
Duplicate of #953, #966
